version: '3'

services:

# http://localhost:8000/segment
  segmentation:
    build:
      context: ./segmentation
    image: athene-segmentation
    container_name: athene-segmentation
    ports:
      - 8000:8000
    working_dir: /usr/src/app
    networks:
      - athene

# http://localhost:8001/embed
  embedding:
    build:
      context: ./embedding
    image: athene-embedding
    container_name: athene-embedding
    ports:
      - 8001:8000
    working_dir: /usr/src/app
    networks:
      - athene

# http://localhost:8002/cluster
  clustering:
    build:
      context: ./clustering
    image: athene-clustering
    container_name: athene-clustering
    ports:
      - 8002:8000
    working_dir: /usr/src/app
    networks:
      - athene

networks:
  athene:
    driver: bridge
