version: '3'

services:

# http://localhost:8000/segment
  segmentation:
    build:
      context: ./segmentation
    image: athene-segmentation
    container_name: athene-segmentation
    ports:
      - 8000:8000
    working_dir: /usr/src/app
    networks:
      - athene

# http://localhost:8001/embed
  embedding:
    build:
      context: ./
      dockerfile: ./embedding/Dockerfile
    image: athene-embedding
    container_name: athene-embedding
    ports:
      - 8001:8000
    working_dir: /usr/src/app
    networks:
      - athene

# http://localhost:8002/cluster
  clustering:
    build:
      context: ./clustering
    image: athene-clustering
    container_name: athene-clustering
    ports:
      - 8002:8000
    working_dir: /usr/src/app
    networks:
      - athene

  database:
    image: mongo:latest
    restart: always
    container_name: athene-mongodb
    expose:
      - 27017
    environment:
      - MONGO_INITDB_DATABASE=athene_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root_password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/db:/data/db
    networks:
      - athene

networks:
  athene:
    driver: bridge
