## Dynamic configuration
http:
  routers:
    # http://localhost/test
    test:
      # catchall
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: test
      priority: 1
    # http://localhost/queueStatus
    # http://localhost/submit
    # http://localhost/getTask
    # http://localhost/sendTaskResult
    balancer:
      rule: "Path(`/queueStatus`,`/submit`,`/getTask`,`/sendTaskResult`)"
      entryPoints:
        - web
      service: balancer
    # http://localhost/trigger
    # http://localhost/segment
    segmentation:
      rule: "Path(`/trigger`,`/segment`)"
      entryPoints:
        - web
      service: segmentation
    # http://localhost/upload
    # http://localhost/feedback_consistency
    embedding:
      rule: "Path(`/upload`,`/feedback_consistency`)"
      entryPoints:
        - web
      service: embedding
    # http://localhost/trigger
    clustering:
      rule: "Path(`/trigger`)"
      entryPoints:
        - web
      service: clustering
    # http://localhost/tracking
    tracking:
      rule: "Path(`/tracking`)"
      entryPoints:
        - web
      service: tracking
  services:
    test:
      loadBalancer:
        servers: {}
    balancer:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:8000"
    segmentation:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:8001"
    embedding:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:8002"
    clustering:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:8003"
    tracking:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:8004"
