# Download WMT dense 24 wide model from facebook
# https://github.com/pytorch/fairseq/tree/main/examples/wmt21

#ToDo download wmt model from transformers
models:
    git clone https://huggingface.co/facebook/wmt21-dense-24-wide-x-en ./models

#nicht das richtige model
#wmt21.dense-24-wide.X-En:
#	@curl "https://dl.fbaipublicfiles.com/fairseq/models/wmt21.dense-24-wide.X-En.tar.gz" | tar xz


#wmt21.dense-24-wide.X-En:
#	@curl "https://huggingface.co/facebook/wmt21-dense-24-wide-x-en"

