compute_nodes:
  - name: athene01
    url: http://athene01.ase.in.tum.de:8001/embed
    chunk_size: 50
    compute_power: 1
    communication_cost: 1
  - name: athene02
    url: http://athene02.ase.in.tum.de:8001/embed
    chunk_size: 50
    compute_power: 1
    communication_cost: 1
  - name: athene03
    url: http://athene03.ase.in.tum.de:8001/embed
    chunk_size: 50
    compute_power: 1
    communication_cost: 1
