# Docker configuration backend
providers:
  docker:
    exposedbydefault: false
    endpoint: "unix:///var/run/docker.sock"
#    swarmMode: true

# Entrypoint configuration
entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

# API and dashboard configuration
api:
  dashboard: true
  insecure: true
