# Downlaad ELMo model from AllenNLP
# https://allennlp.org/elmo

deps: elmo_2x4096_512_2048cnn_2xhighway_5.5B
elmo_2x4096_512_2048cnn_2xhighway_5.5B: elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5 elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json

elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5:
	@curl -OJ "https://nextcloud.in.tum.de/index.php/s/xB7QitYX2ydbSpC/download"

elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json:
	@curl -OJ "https://nextcloud.in.tum.de/index.php/s/itNpqDHE8NqpBgy/download"