# Configure compute nodes being managed by docker swarm and registered to traefik
docker_nodes:
  # This url resolves to the API of the traefik-container inside the docker-network started in a docker swarm
  - traefik_service_api: http://tasks.traefik:8080/api/http/services/
    segmentation_service_name: segmentation@docker
    embedding_service_name: upload@docker
    clustering_service_name: clustering@docker
    trigger_route: /trigger

# Configure stand-alone compute nodes
#compute_nodes:
#  - name: segmentation-stand-alone
#    # This url resolves to the segmentation-container inside the docker-swarm network
#    trigger_url: http://tasks.segmentation.<container-id>:8000/trigger
#    type: segmentation
