# Downlaad ELMo model from AllenNLP
# https://allennlp.org/elmo

deps: weights_files

weights_files:
	@curl -OJ "https://nextcloud.in.tum.de/index.php/s/Laomj7zHJnqHc4L/download"
	@unzip models.zip
	@rm models.zip

