name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the text-assessment-clustering Docker image
      run: cd Clustering; docker build . --file Dockerfile --tag text-assessment-clustering:$(date +%s)    
    - name: Build the text-segmentation Docker image
      run: cd Segmentation; docker build . --file Dockerfile --tag text-segmentation:$(date +%s)