name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${GITHUB_ACTOR}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push the athene-segmentation Docker image
      run: |
        TAG=$(git rev-parse --short "$GITHUB_SHA")
        REGISTRY=docker.pkg.github.com
        IMAGE=${REGISTRY}/ls1intum/athene/athene-segmentation
        cd Segmentation; docker build . --file Dockerfile --tag ${IMAGE}:${TAG}
        docker push ${IMAGE}:${TAG}
        docker tag ${IMAGE}:${TAG} ${IMAGE}:${GITHUB_REF##*/}
        docker push ${IMAGE}:${GITHUB_REF##*/}
    - name: Build and Push the athene-clustering Docker image
      run: |
        REGISTRY=docker.pkg.github.com
        IMAGE=${REGISTRY}/ls1intum/athene/athene-clustering
        TAG=$(git rev-parse --short "$GITHUB_SHA")
        cd Clustering; docker build . --file Dockerfile --tag ${IMAGE}:${TAG}
        docker push ${IMAGE}
        docker tag ${IMAGE}:${TAG} ${IMAGE}:${GITHUB_REF##*/}
        docker push ${IMAGE}:${GITHUB_REF##*/}