name: Docker Image CI

on: [push]

jobs:

  athene-load-balancer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${GITHUB_ACTOR}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: github.ref == 'refs/heads/master'
    - name: Build and Push the athene-load-balancer Docker image
      run: ./.github/workflows/scripts/dockerimage.sh "load-balancer"

  athene-segmentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${GITHUB_ACTOR}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: github.ref == 'refs/heads/master'
    - name: Build and Push the athene-segmentation Docker image
      run: ./.github/workflows/scripts/dockerimage.sh "segmentation"

  athene-embedding:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${GITHUB_ACTOR}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: github.ref == 'refs/heads/master'
    - name: Build and Push the athene-embedding Docker image
      run: ./.github/workflows/scripts/dockerimage.sh "embedding"
    - name: Run unittests for embedding-component
      run: docker run -i --rm --entrypoint python docker.pkg.github.com/ls1intum/athene/athene-embedding:${GITHUB_REF##*/} -m unittest discover -p test_*.py

  athene-clustering:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${GITHUB_ACTOR}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: github.ref == 'refs/heads/master'
    - name: Build and Push the athene-clustering Docker image
      run: ./.github/workflows/scripts/dockerimage.sh "clustering"
    - name: Run unittests for clustering-component
      run: docker run -i --rm --entrypoint python docker.pkg.github.com/ls1intum/athene/athene-clustering:${GITHUB_REF##*/} -m unittest discover -p test_*.py

  athene-tracking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${GITHUB_ACTOR}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: github.ref == 'refs/heads/master'
    - name: Build and Push the athene-tracking Docker image
      run: ./.github/workflows/scripts/dockerimage.sh "tracking"
